version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  
  mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    expose:
      - 27017

volumes:
  mongodb-data: